# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM_Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SwiftyJSON'
pod 'MBProgressHUD'
pod 'Reachability'
pod 'Alamofire', '~> 5.2'
pod 'Kingfisher'

  # Pods for MVVM_Demo

end
