# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM_Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SwiftyJSON'
pod 'MBProgressHUD'
pod 'Reachability'
pod 'Alamofire', '~> 5.2'
pod 'Kingfisher'
pod 'Then'
pod 'Reusable'

# Rx
pod 'RxSwift'
pod 'NSObject+Rx'
pod 'RxDataSources'

# Clean Architecture
pod 'MGArchitecture'

  # Pods for MVVM_Demo

end
